---
- name: Duct-Tape for Update all packages! Debian
  copy:
    content: "{{ansible_date_time.date}}"
    dest: /opt/sytem_update_timestamp
    force: no
    group: root
    owner: root
    mode: 0444
  register: updated

- name: Upgrade all packages RHEL
  yum:
    name: '*'
    state: latest
  when: updated.changed

- name: Check if EPEL repo is already configured. and Duct-Tape for Update all packages!
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
 
- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: Install RHEL Packages
  package:
    name: "{{ package_list_rhel }}"
    state: present